[package]
name = "chamsae"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
async-trait = "0.1.72"
axum = { version = "0.6.20", features = ["headers"] }
bcrypt = "0.15.0"
envy = "0.4.2"
migration = { version = "0.1.0", path = "../migration" }
once_cell = "1.18.0"
sea-orm = { version = "0.12.2", default-features = false, features = ["macros", "with-json", "with-rust_decimal", "with-bigdecimal", "with-uuid", "sqlx-postgres", "runtime-tokio-rustls", "with-time"] }
serde = { version = "1.0.182", features = ["derive"] }
time = "0.3.25"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros", "signal"] }
tower-http = { version = "0.4.3", features = ["fs"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "fmt"] }
ulid = { version = "1.0.0", features = ["serde"] }
url = { version = "2.4.0", features = ["serde"] }
