name: frontend-build
run-name: "Frontend: build"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: frontend-yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            frontend-yarn-${{ runner.os }}-
      - name: Install dependencies
        working-directory: frontend
        run: yarn --immutable
      - name: Build
        working-directory: frontend
        run: yarn build
